### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [madgen/madgen.github.io#1]
Hi @madgen! Thanks again for submitting your content to issue 94 of Haskell Weekly (https://github.com/haskellweekly/haskellweekly.github.io/pull/154). I like to follow authors that have been featured in Haskell Weekly, but as far as I can tell your blog doesn't have a feed. Would you mind adding one? Your site is apparently built with Hakyll, which supports feeds out of the box: https://jaspervdj.be/hakyll/tutorials/05-snapshots-feeds.html

**Comment by madgen** [comment]
Thanks for this. I added [atom feed](https://dodisturb.me/atom.xml) which should be discoverable.

**Comment by madgen** [comment]
Thanks for this. I added an [atom feed](https://dodisturb.me/atom.xml) (I think).

**Comment by tfausak** [comment]
Looks great to me! Thanks so much!
